### ISSUE TITLE
adding support for Numpy structured arrays via `MPI_Type_create_struct`

### ISSUE THREAD

**Issue by jpmorgan98** [numba-mpi/numba-mpi#119]
Are there any current plans to support [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) functionality with numba-mpi? If not how difficult would it be to implement?

I work with a Monte Carlo neutronics package called [mc/dc](https://github.com/CEMeNT-PSAAP/MCDC) and we use ndarrays as our primary data structure. Sorry if this isn't the ideal way to ask but this project is very exciting! Thanks!

**Comment by slayoo** [comment]
@jpmorgan98, thanks for posting.
Numpy ndarrays are the basic data type that we do support - see, e.g., the example in the README file where both `src` and `dst_tst` are ndarrays. Please elaborate on the actual use case, thanks.

**Comment by spasmann** [comment]
Hi @slayoo, I'm another mc/dc developer, thanks for you reply! A little more detail about our problem..

We communicate numpy arrays  of "particles". Each particle is a custom numpy datatype built like this
```python
def make_type_particle_record():
    global particle_record
    struct = [
        ("x", np.float64),
        ("y", np.float64),
        ("z", np.float64),
        ("t", np.float64),
        ("ux", np.float64),
        ("uy", np.float64),
        ("uz", np.float64),
        ("g", np.uint64),
        ("w", np.float64),
        ("sensitivity_ID", np.int64),
        ("rng_seed", np.uint64),
    ]
    particle_record = np.dtype(struct)
```

Most of MC/DC is accelerated with Numba. However, our send/recv calls from mpi4py occur in `objmode()` for obvious reasons. Your package would be perfect for getting rid of the `objmode()`, but when I naively swap our mpi4py send/recv calls with numba-mpi calls I get the following error:
```
Traceback (most recent call last):
  File "/Users/sam/Documents/GitHub/MCDC/examples/fixed_source/slab_reed_iqmc/input.py", line 105, in <module>
    mcdc.run()
  File "/Users/sam/Documents/GitHub/MCDC/mcdc/main.py", line 80, in run
    loop_iqmc(mcdc)
  File "/Users/sam/Documents/GitHub/MCDC/mcdc/loop.py", line 495, in loop_iqmc
    source_iteration(mcdc)
  File "/Users/sam/Documents/GitHub/MCDC/mcdc/loop.py", line 551, in source_iteration
    iqmc_loop_source(mcdc)
  File "/Users/sam/Documents/GitHub/MCDC/mcdc/loop.py", line 532, in iqmc_loop_source
    kernel.iqmc_improved_kull(mcdc)
  File "/Users/sam/Documents/GitHub/MCDC/mcdc/kernel.py", line 3181, in iqmc_improved_kull
    mpi.isend(send_bank, dest=mcdc["technique"][name][i])
  File "/Users/sam/mambaforge/envs/mcdc_env/lib/python3.10/site-packages/numba_mpi/api/isend.py", line 32, in isend
    _mpi_dtype(data),
  File "/Users/sam/mambaforge/envs/mcdc_env/lib/python3.10/site-packages/numba_mpi/utils.py", line 10, in _mpi_dtype
    ptr = _get_dtype_numpy_to_mpi_ptr(arr)
  File "/Users/sam/mambaforge/envs/mcdc_env/lib/python3.10/site-packages/numba_mpi/utils.py", line 41, in _get_dtype_numpy_to_mpi_ptr
    raise NotImplementedError(f"Type: {arr.dtype}")
NotImplementedError: Type: [('x', '<f8'), ('y', '<f8'), ('z', '<f8'), ('t', '<f8'), ('ux', '<f8'), ('uy', '<f8'), ('uz', '<f8'), ('g', '<u8'), ('w', '<f8'), ('sensitivity_ID', '<i8'), ('rng_seed', '<u8'), ('iqmc', [('w', '<f8', (1,))])]
``

I think our most immediate question is does numba-mpi support sending arrays of datatypes like the one we have above?

**Comment by slayoo** [comment]
@spasmann thank you for clarifying; numba-mpi aims to offer wrappers over the C API of MPI, so here we would need to wrap `MPI_Type_create_struct` which is not available yet, and would likely be a major development to add.

Still, it should be possible to write njittable code for sending/receiving individual components of your structured datatype - i.e. some pack/unpack logic.

(@jpmorgan98, will rename the issue to include the MPI_Type_create_struct keyword)

**Comment by slayoo** [comment]
Relevant resources:
- https://stackoverflow.com/questions/9864510/struct-serialization-in-c-and-transfer-over-mpi
- https://numpy.org/doc/stable/user/basics.rec.html
- https://mpi4py.readthedocs.io/en/stable/reference/mpi4py.MPI.Datatype.html?highlight=struct#mpi4py.MPI.Datatype.Create_struct
- https://www.open-mpi.org/doc/v4.0/man3/MPI_Type_create_struct.3.php

**Comment by Grzyb33k** [comment]
Hi @jpmorgan98, @spasmann,

I’m planning to work on adding support for structured MPI datatypes under @slayoo's supervision.

I want to make sure I fully understand the requirements from a user’s perspective. Could you provide a "Hello World" example that represents how you would like to use structured arrays with numba-mpi?

Additionally, if you have a more complex case study or a representative benchmark from the mc/dc project, it would be helpful for evaluating the performance of my solution later on.

Looking forward to your feedback!
